<template>
  <section class="space-y-7">
    <div class="max-w-3xl"><p class="mb-2 text-sm font-bold uppercase tracking-[0.18em] text-plum">Preference import</p><h1 class="text-3xl font-bold tracking-tight text-ink sm:text-4xl">Convert MBA student survey results.</h1><p class="mt-3 text-lg leading-8 text-slate-600">Turn each student's ranked corporate board internship preferences into a clean matrix for optimal matching.</p></div>
    <div class="grid items-center gap-3 rounded-2xl border border-purple-100 bg-purple-50 p-4 text-center text-sm font-semibold text-ink sm:grid-cols-[1fr_auto_1fr_auto_1fr] sm:text-left"><div class="rounded-xl bg-white px-4 py-3 shadow-sm"><span class="block text-xs uppercase tracking-wide text-slate-500">Start with</span>Qualtrics CSV export</div><span class="text-xl text-plum" aria-hidden="true">→</span><div class="rounded-xl bg-white px-4 py-3 shadow-sm"><span class="block text-xs uppercase tracking-wide text-slate-500">Convert to</span>Student preference matrix</div><span class="text-xl text-plum" aria-hidden="true">→</span><div class="rounded-xl bg-white px-4 py-3 shadow-sm"><span class="block text-xs uppercase tracking-wide text-slate-500">Then use</span>Optimal matching</div></div>
    <article class="card overflow-hidden"><div class="border-b border-slate-100 bg-gradient-to-r from-white to-purple-50 px-5 py-5 sm:px-7"><p class="text-sm font-bold text-plum">Step 1 · Paste your export</p><h2 class="mt-1 text-xl font-bold text-ink">Qualtrics survey results</h2><p class="mt-1 text-sm leading-6 text-slate-600">In Qualtrics, export all fields using choice text, then paste the CSV contents below.</p></div><div class="p-5 sm:p-7"><label class="field-label" for="qualtrics-input">MBA student preference survey export</label><textarea id="qualtrics-input" v-model="csvInput" rows="12" class="text-input font-mono text-sm leading-6" placeholder="Paste your Qualtrics CSV here…"></textarea><p v-if="error" class="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{{ error }}</p></div></article>
    <article class="card overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 px-5 py-5 sm:px-7"><div><p class="text-sm font-bold text-plum">Step 2 · Confirm import settings</p><h2 class="mt-1 text-xl font-bold text-ink">Configure your export</h2></div><button class="secondary-button text-sm" type="button" @click="showSettings = !showSettings">{{ showSettings ? 'Hide settings' : 'Edit settings' }}</button></div><div v-if="showSettings" class="grid gap-5 p-5 sm:grid-cols-3 sm:p-7"><label><span class="field-label">Student ID column</span><input v-model="studentIdColLabel" class="text-input" /></label><label><span class="field-label">Question text row</span><input v-model.number="questionTextRow" min="0" type="number" class="text-input" /></label><label><span class="field-label">Data starts on row</span><input v-model.number="dataStartRow" min="0" type="number" class="text-input" /></label></div><div v-else class="px-5 py-4 text-sm text-slate-600">Using column <strong>{{ studentIdColLabel }}</strong>, question row <strong>{{ questionTextRow + 1 }}</strong>, and data from row <strong>{{ dataStartRow + 1 }}</strong>.</div></article>
    <article v-if="csvInput" class="card overflow-hidden"><div class="border-b border-slate-100 px-5 py-5 sm:px-7"><p class="text-sm font-bold text-plum">Step 3 · Review and use</p><h2 class="mt-1 text-xl font-bold text-ink">Converted preference matrix</h2></div><div class="grid gap-px border-b border-slate-100 bg-slate-100 sm:grid-cols-2"><div class="bg-white px-5 py-4"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Students detected</p><p class="mt-1 text-2xl font-bold text-ink">{{ studentNames.length }}</p><p class="mt-1 truncate text-sm text-slate-500">{{ studentNames.slice(0, 4).join(', ') || 'No students detected' }}</p></div><div class="bg-white px-5 py-4"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Companies detected</p><p class="mt-1 text-2xl font-bold text-ink">{{ companyNames.length }}</p><p class="mt-1 truncate text-sm text-slate-500">{{ companyNames.slice(0, 4).join(', ') || 'No companies detected' }}</p></div></div><div class="p-5 sm:p-7"><label class="field-label" for="matrix-output">Rankings matrix output</label><textarea id="matrix-output" :value="output" readonly rows="10" class="text-input bg-slate-50 font-mono text-sm leading-6"></textarea><div class="mt-5 flex flex-wrap gap-3"><button class="primary-button" type="button" :disabled="!output" @click="copyOutput">{{ copied ? 'Copied to clipboard' : 'Copy matrix' }}</button><RouterLink to="/" class="secondary-button">Open optimizer <span aria-hidden="true">→</span></RouterLink></div></div></article>
  </section>
</template>

<script setup>
import { computed, ref } from 'vue'
import Papa from 'papaparse'

const csvInput = ref(''), studentIdColLabel = ref('Q2'), questionTextRow = ref(1), dataStartRow = ref(3), showSettings = ref(false), copied = ref(false)
const companyPattern = /- Ranks - My Top 10 - (?<company>.*) - Rank/
const parsed = computed(() => Papa.parse(csvInput.value).data)
const error = computed(() => csvInput.value && parsed.value.length <= dataStartRow.value ? 'This export does not contain enough rows for the selected settings.' : '')
const columnLabels = computed(() => parsed.value[0] || [])
const questionTexts = computed(() => parsed.value[questionTextRow.value] || [])
const students = computed(() => { const column = columnLabels.value.indexOf(studentIdColLabel.value); if (column < 0) return []; return parsed.value.slice(dataStartRow.value).map((row, index) => ({ name: row[column], row: index + dataStartRow.value })).filter(({ name }) => name) })
const companies = computed(() => questionTexts.value.map((text, column) => ({ match: String(text || '').match(companyPattern), column })).filter(({ match }) => match).map(({ match, column }) => ({ name: match.groups.company, column })))
const studentNames = computed(() => students.value.map(({ name }) => name))
const companyNames = computed(() => companies.value.map(({ name }) => name))
const output = computed(() => { if (!students.value.length || !companies.value.length) return ''; return Papa.unparse([['Student ID', ...companyNames.value], ...students.value.map(student => [student.name, ...companies.value.map(company => parsed.value[student.row]?.[company.column] || '')])]) })
async function copyOutput() { await navigator.clipboard.writeText(output.value); copied.value = true; window.setTimeout(() => { copied.value = false }, 1800) }
</script>
